const ExtractData = [
    {
    id: 1,
    operacao: 'Pagamento Efetuado',
    type: 'debito',
    dataOperacao: "2022-05-02",
    icone: 'boleto',
    valor: 5500.50,
    destinatario: "Banco Inter",
    },
    {
    id: 2,
    operacao: 'Pagamento Efetuado',
    type: 'debito',
    dataOperacao: "2022-05-15",
    icone: 'pix',
    valor: 550.50,
    destinatario: "Banco Caixa",
    },
    {
    id: 3,
    operacao: 'Transação Recebida',
    type: 'debito',
    dataOperacao: "2022-05-06",
    icone: 'pix',
    valor: 500.00,
    destinatario: "Banco C6",
    },
    {
    id: 4,
    operacao: 'Transação Recebida',
    type: 'credito',
    dataOperacao: "2022-05-20",
    icone: 'boleto',
    valor: 5500,
    destinatario: "Banco Inter",
    },
    {
    id: 5,
    operacao: 'Pagamento Recebido',
    type: 'debito',
    dataOperacao: "2022-05-23",
    icone: 'boleto',
    valor: 5500.50,
    destinatario: "Banco Inter",
    },
    {
    id: 6,
    operacao: 'Pagamento Efetuado',
    type: 'debito',
    dataOperacao: "2022-05-02",
    icone: 'pix',
    valor: 100.00,
    destinatario: "Banco Brasil",
    },
    {
    id: 7,
    operacao: 'Pagamento Efetuado',
    type: 'credito',
    dataOperacao: "2022-05-01",
    icone: 'boleto',
    valor: 7400.00,
    destinatario: "Banco Inter",
    },
    {
    id: 8,
    operacao: 'Pagamento Efetuado',
    type: 'debito',
    dataOperacao: "2022-05-08",
    icone: 'boleto',
    valor: 2222.00,
    destinatario: "Banco Inter",
    },
    {
    id: 9,
    operacao: 'Pagamento Efetuado',
    type: 'debito',
    dataOperacao: "2022-05-02",
    icone: 'boleto',
    valor: 50.50,
    destinatario: "Banco Inter",
    },
    {
    id: 10,
    operacao: 'Pagamento Efetuado',
    type: 'debito',
    dataOperacao: "2022-05-11",
    icone: 'boleto',
    valor: 550,
    destinatario: "Banco Inter",
    },
];

export default ExtractData;